// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBql5kSkNQmb9ch6EeZLZFMSd3zZ3BafKg',
    appId: '1:225816305953:web:f81ebaacf5b14b15471e60',
    messagingSenderId: '225816305953',
    projectId: 'car-store-9f1c0',
    authDomain: 'car-store-9f1c0.firebaseapp.com',
    storageBucket: 'car-store-9f1c0.firebasestorage.app',
    measurementId: 'G-EQ4TBGWE1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHsoHBTp6sPkj1ognoix_eWRaIi1AJM_8',
    appId: '1:225816305953:android:f2928da12f02e35b471e60',
    messagingSenderId: '225816305953',
    projectId: 'car-store-9f1c0',
    storageBucket: 'car-store-9f1c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqiXOYBR5LU67N0Z4-luaqQWoV9PDVeG0',
    appId: '1:225816305953:ios:cc4d214abf8b01ed471e60',
    messagingSenderId: '225816305953',
    projectId: 'car-store-9f1c0',
    storageBucket: 'car-store-9f1c0.firebasestorage.app',
    iosBundleId: 'com.example.carStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqiXOYBR5LU67N0Z4-luaqQWoV9PDVeG0',
    appId: '1:225816305953:ios:cc4d214abf8b01ed471e60',
    messagingSenderId: '225816305953',
    projectId: 'car-store-9f1c0',
    storageBucket: 'car-store-9f1c0.firebasestorage.app',
    iosBundleId: 'com.example.carStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBql5kSkNQmb9ch6EeZLZFMSd3zZ3BafKg',
    appId: '1:225816305953:web:afb9e3196de179a5471e60',
    messagingSenderId: '225816305953',
    projectId: 'car-store-9f1c0',
    authDomain: 'car-store-9f1c0.firebaseapp.com',
    storageBucket: 'car-store-9f1c0.firebasestorage.app',
    measurementId: 'G-SFX36SRETH',
  );
}
